// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq36PWVaqrmtkcQsdbU1rZZgZHSH0WMZc',
    appId: '1:264894526858:web:cabc6590fd3ee4b8a68473',
    messagingSenderId: '264894526858',
    projectId: 'flutterchat-ab0a9',
    authDomain: 'flutterchat-ab0a9.firebaseapp.com',
    storageBucket: 'flutterchat-ab0a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtiEB8gj97LfDgYIq-RVPez4q-spO0PI8',
    appId: '1:264894526858:android:34998a762d653b43a68473',
    messagingSenderId: '264894526858',
    projectId: 'flutterchat-ab0a9',
    storageBucket: 'flutterchat-ab0a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQswQJSqfNAA9EZEH51loGf_hjAy3hBxI',
    appId: '1:264894526858:ios:ba62addb944a1965a68473',
    messagingSenderId: '264894526858',
    projectId: 'flutterchat-ab0a9',
    storageBucket: 'flutterchat-ab0a9.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQswQJSqfNAA9EZEH51loGf_hjAy3hBxI',
    appId: '1:264894526858:ios:bd3efb02696e1a1ca68473',
    messagingSenderId: '264894526858',
    projectId: 'flutterchat-ab0a9',
    storageBucket: 'flutterchat-ab0a9.appspot.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
